### ISSUE TITLE
Landscape not smooth

### ISSUE THREAD

**Issue by henres** [delebash/UnrealMapboxBridgePlugin#2]
Hello,
I try to use your awesome tool.
But the rendering is weird.
I have this scale, see my screenshot.

![landscape_scale](https://user-images.githubusercontent.com/866305/232851799-b3666150-2d88-4cde-b570-d9c55e9fec0b.jpeg)

Do you have settings to set to have a smoother render ?

Thanks in advance

**Comment by delebash** [comment]
This happens usually if you zoom to close or on low elevation sites.  There is nothing I can do about this because it is a resolution issue on the files from mapbox.  Try zooming out a little bit.  Also here is a manual work around  https://www.youtube.com/watch?v=C9KgoFfIYhE&list=PLFCVXzupw1r_7ExUSGDxHGHU-gPRxOGeZ&index=8&t=35s&pp=gAQBiAQB

Also you can try increasing the Blur radius value on the Side Menu.  The higher the number the more blur which should help smooth the image.

**Comment by henres** [comment]
Ok, I will try that, thanks a lot!
